export const catalogList = [
  {
    name: "אבוקדו האס",
    price: 20,
    count_step: 1,
    unit: 'ק"ג',
    img_path: "/avocado.jpeg",
    description: "כי אין כמו מצה עם אבוקדו",
    unit_count: 1.5,
    id: 1,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "תפוח עץ סמיט",
    price: 15,
    count_step: 1,
    unit: "נספק",
    img_path: "/gala.jpeg",
    description: null,
    unit_count: 1,
    id: 16,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "תפוח עץ פינק ליידי",
    price: 19,
    count_step: 1,
    unit: "נספק",
    img_path: "/pink-lady.jpeg",
    description: null,
    unit_count: 1,
    id: 18,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "תפוז",
    price: 20,
    count_step: 1,
    unit: "שקים",
    img_path: "/oranges2.jpeg",
    description: 'שקים של 5 ק"ג',
    unit_count: 1,
    id: 44,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "אננס קטן",
    price: 25,
    count_step: 1,
    unit: "יחידות",
    img_path: "/pineapple.jpeg",
    description: null,
    unit_count: 1,
    id: 46,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "שמן זית כבישה קרה 1 ליטר",
    price: 48,
    count_step: 1,
    unit: "ליטר",
    img_path: "/olive-oil.jfif",
    description: null,
    unit_count: 1,
    id: 49,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "שמן זית כבישה קרה 2 ליטר",
    price: 85,
    count_step: 1,
    unit: "ליטר",
    img_path: "/olive-oil.jfif",
    description: null,
    unit_count: 2,
    id: 50,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "שום ישראלי טרי",
    price: 27,
    count_step: 0.5,
    unit: "קילו",
    img_path: "/garlic.jpeg",
    description: null,
    unit_count: 1,
    id: 55,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "פקאן",
    price: 30,
    count_step: 1,
    unit: 'ק"ג',
    img_path: "/pecan.jpeg",
    description: "אורגני וטרי",
    unit_count: 1,
    id: 79,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "שסק",
    price: 25,
    count_step: 1,
    unit: "נספק",
    img_path: "/shesek.jpeg",
    description: null,
    unit_count: 1,
    id: 65,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "דבש קילו",
    price: 45,
    count_step: 1,
    unit: 'ק"ג',
    img_path: "/honey.jpeg",
    description: null,
    unit_count: 1,
    id: 42,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "אננס גדול",
    price: 40,
    count_step: 1,
    unit: "יחידות",
    img_path: "/pineapple.jpeg",
    description: null,
    unit_count: 1,
    id: 45,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "דבש חצי קילו",
    price: 25,
    count_step: 1,
    unit: 'ק"ג',
    img_path: "/honey.jpeg",
    description: null,
    unit_count: 0.5,
    id: 43,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "עגבניות שרי ליקופן",
    price: 19,
    count_step: 1,
    unit: "נספק",
    img_path: "/shery-tomato1.jpeg",
    description: null,
    unit_count: 1,
    id: 11,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "עגבניות שרי תמר",
    price: 19,
    count_step: 1,
    unit: "נספק",
    img_path: "/sherry2.jpeg",
    description: null,
    unit_count: 1,
    id: 12,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "תפוח עץ גאלה",
    price: 15,
    count_step: 1,
    unit: "נספק",
    img_path: "/gala.jpeg",
    description: null,
    unit_count: 1,
    id: 19,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "בננה",
    price: 12,
    count_step: 1,
    unit: "נספק",
    img_path: "/banana.jfif",
    description: null,
    unit_count: 1,
    id: 62,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "אגס",
    price: 17,
    count_step: 1,
    unit: "נספק",
    img_path: "/pear.jpeg",
    description: null,
    unit_count: 1,
    id: 51,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "אבטיח",
    price: 10,
    count_step: 1,
    unit: 'ק"ג',
    img_path: "/watermelon.jpeg",
    description: null,
    unit_count: 1,
    id: 80,
    estimate_quantity_per_unit: 7,
  },
  {
    name: "חסה עגולה",
    price: 12,
    count_step: 1,
    unit: "חבילה",
    img_path: "/lettus.jpeg",
    description: null,
    unit_count: 1,
    id: 85,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "כרובית",
    price: 15,
    count_step: 1,
    unit: "יחידה",
    img_path: "/collyflower.jpeg",
    description: null,
    unit_count: 1,
    id: 75,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "מלפפון",
    price: 7,
    count_step: 0.5,
    unit: 'ק"ג',
    img_path: "/cucumber.jpeg",
    description: null,
    unit_count: 1,
    id: 74,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "מלפפון בייבי",
    price: 12,
    count_step: 1,
    unit: "חבילה",
    img_path: "/baby-cucumber.jpeg",
    description: null,
    unit_count: 1,
    id: 84,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "עגבניות חממה",
    price: 9,
    count_step: 0.5,
    unit: 'ק"ג',
    img_path: "/tomatoes.jpeg",
    description: null,
    unit_count: 1,
    id: 10,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "ענבים שחורים",
    price: 32,
    count_step: 1,
    unit: 'ק"ג',
    img_path: "/black-grapes.jpeg",
    description: "ללא חרצנים",
    unit_count: 1,
    id: 77,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "פלפל אדום",
    price: 10,
    count_step: 0.5,
    unit: 'ק"ג',
    img_path: "/red-pepper.jpeg",
    description: null,
    unit_count: 1,
    id: 83,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "פלפל שושקה",
    price: 20,
    count_step: 0.5,
    unit: 'ק"ג',
    img_path: "/pepper-shushka.jpeg",
    description: "פלפל אדום מתוק",
    unit_count: 1,
    id: 81,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "לבבות חסה",
    price: 12,
    count_step: 1,
    unit: "נספק",
    img_path: "/lettus.jpeg",
    description: null,
    unit_count: 1,
    id: 66,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "אפרסק לבן",
    price: 37,
    count_step: 0.5,
    unit: 'ק"ג',
    img_path: "/peach.jpeg",
    description: null,
    unit_count: 1,
    id: 82,
    estimate_quantity_per_unit: 1,
  },
  {
    name: "מלון כתום",
    price: 15,
    count_step: 1,
    unit: "יחידה",
    img_path: "/melon.jpeg",
    description: "ריחני וטעים במיוחד!",
    unit_count: 1,
    id: 76,
    estimate_quantity_per_unit: 1,
  },
];
